baseURL = "https://optimistic-kare-e17eb0.netlify.com/"
languageCode = "en-us"
title = "The chess atlas"


[menu]
  [[menu.main]]
    indentifier = "home"
    name = "Home"
    url = "/"
    weight = 10